# Generated by Django 2.0.8 on 2018-09-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180927_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentosPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVencimento', models.DateField()),
                ('dataEmissao', models.DateField()),
                ('valorTitulo', models.TextField(max_length=14)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('Empresa_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresas')),
                ('Fornecedor_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Fornecedores')),
            ],
        ),
    ]
