# Generated by Django 2.0.8 on 2018-09-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lancamentospagar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=14)),
                ('numero', models.CharField(max_length=15)),
                ('dataVencimento', models.DateField()),
                ('dataEmissao', models.DateField()),
                ('dataDisponibilidade', models.DateField()),
                ('Cliente_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Clientes')),
                ('Empresa_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresas')),
                ('FormaPagamento_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.FormasPagamento')),
                ('Fornecedor_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Fornecedores')),
                ('PlanoDeContas_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PlanosDeContas')),
            ],
        ),
    ]
