# Generated by Django 2.0.8 on 2018-10-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181003_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'TiposPessoas',
            },
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='tipoPessoa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='tipoPessoa',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='tipoPessoa',
        ),
    ]
