# Generated by Django 2.0.8 on 2018-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181003_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosdecontas',
            name='entradaRecurso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planosdecontas',
            name='saidaRecurso',
            field=models.BooleanField(default=False, verbose_name='tap status'),
        ),
    ]
