# Generated by Django 2.0.8 on 2018-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181005_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='inscricaoEstadual',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='razaoSocial',
        ),
        migrations.AddField(
            model_name='empresas',
            name='inscricao_estadual',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='razao_Social',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='caixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planosdecontas',
            name='banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planosdecontas',
            name='caixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planosdecontas',
            name='cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planosdecontas',
            name='fornecedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planosdecontas',
            name='saidaRecurso',
            field=models.BooleanField(default=False),
        ),
    ]
