# Generated by Django 2.0.8 on 2018-10-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181005_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baixaspagar',
            name='FormaPagamento_Id',
        ),
        migrations.RemoveField(
            model_name='baixaspagar',
            name='LancamentoReceber_Id',
        ),
        migrations.RemoveField(
            model_name='baixasreceber',
            name='FormaPagamento_Id',
        ),
        migrations.RemoveField(
            model_name='baixasreceber',
            name='LancamentoReceber_Id',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='tipoPessoa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='tipoPessoa',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='tipoPessoa',
        ),
        migrations.RemoveField(
            model_name='lancamentospagar',
            name='Empresa_Id',
        ),
        migrations.RemoveField(
            model_name='lancamentospagar',
            name='Fornecedor_Id',
        ),
        migrations.RemoveField(
            model_name='lancamentosreceber',
            name='Cliente_Id',
        ),
        migrations.RemoveField(
            model_name='lancamentosreceber',
            name='Empresa_Id',
        ),
        migrations.RemoveField(
            model_name='planosdecontas',
            name='ContaBancaria_Id',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Cliente_Id',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Empresa_Id',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='FormaPagamento_Id',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Fornecedor_Id',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='PlanoDeContas_Id',
        ),
        migrations.DeleteModel(
            name='BaixasPagar',
        ),
        migrations.DeleteModel(
            name='BaixasReceber',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='ContasBancarias',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='FormasPagamento',
        ),
        migrations.DeleteModel(
            name='Fornecedores',
        ),
        migrations.DeleteModel(
            name='LancamentosPagar',
        ),
        migrations.DeleteModel(
            name='LancamentosReceber',
        ),
        migrations.DeleteModel(
            name='PlanosDeContas',
        ),
        migrations.DeleteModel(
            name='Tesouraria',
        ),
        migrations.DeleteModel(
            name='TiposPessoa',
        ),
    ]
