# Generated by Django 2.0.8 on 2018-10-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181005_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipospessoa',
            options={'verbose_name_plural': 'Tipos de Pessoas'},
        ),
    ]
