# Generated by Django 2.0.8 on 2018-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181005_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baixaspagar',
            name='Forma_Pagamento',
        ),
        migrations.RemoveField(
            model_name='baixaspagar',
            name='Lancamento_Receber',
        ),
        migrations.RemoveField(
            model_name='baixasreceber',
            name='Forma_Pagamento',
        ),
        migrations.RemoveField(
            model_name='baixasreceber',
            name='Lancamento_Receber',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='tipo_Pessoa',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='tipo_Pessoa',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='tipo_Pessoa',
        ),
        migrations.RemoveField(
            model_name='lancamentospagar',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='lancamentospagar',
            name='Fornecedor',
        ),
        migrations.RemoveField(
            model_name='lancamentosreceber',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='lancamentosreceber',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='planosdecontas',
            name='Conta_Bancaria',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Forma_Pagamento',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Fornecedor',
        ),
        migrations.RemoveField(
            model_name='tesouraria',
            name='Plano_De_Contas',
        ),
        migrations.DeleteModel(
            name='BaixasPagar',
        ),
        migrations.DeleteModel(
            name='BaixasReceber',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='ContasBancarias',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='FormasPagamento',
        ),
        migrations.DeleteModel(
            name='Fornecedores',
        ),
        migrations.DeleteModel(
            name='LancamentosPagar',
        ),
        migrations.DeleteModel(
            name='LancamentosReceber',
        ),
        migrations.DeleteModel(
            name='PlanosDeContas',
        ),
        migrations.DeleteModel(
            name='Tesouraria',
        ),
        migrations.DeleteModel(
            name='TiposPessoa',
        ),
    ]
