# Generated by Django 2.0.8 on 2018-10-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('disponibilidade', models.CharField(max_length=12)),
                ('data_Baixa', models.DateField(blank=True, null=True)),
                ('valor_Pago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'Baixas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='BaixasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('disponibilidade', models.CharField(max_length=12)),
                ('data_Baixa', models.DateField(blank=True, null=True)),
                ('valor_Pago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'Baixas a Receber',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_Social', models.TextField()),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('cnpjCpf', models.CharField(max_length=15)),
                ('inscricao_Estadual', models.CharField(max_length=20)),
                ('inscricao_Municipal', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.TextField()),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.TextField()),
                ('email', models.TextField()),
                ('nome_Titular', models.TextField()),
                ('funcao', models.TextField()),
                ('tipo_Pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TiposPessoa')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=18)),
                ('descricao', models.TextField()),
                ('numeroConta', models.CharField(max_length=20)),
                ('numero_Agencia', models.CharField(max_length=20)),
                ('data_Saldo_Inicial', models.DateField()),
                ('saldo_Inicial', models.CharField(max_length=14)),
                ('caixa', models.BooleanField(default=False)),
                ('banco', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='FormasPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_Social', models.TextField()),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('cnpjCpf', models.CharField(max_length=15)),
                ('inscricao_Estadual', models.CharField(max_length=20)),
                ('inscricao_Municipal', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.TextField()),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.TextField()),
                ('email', models.TextField()),
                ('nome_Titular', models.TextField()),
                ('cpf', models.CharField(max_length=50)),
                ('funcao', models.TextField()),
                ('tipo_Pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TiposPessoa')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='LancamentosPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Vencimento', models.DateField()),
                ('data_Emissao', models.DateField()),
                ('valor_Titulo', models.TextField(max_length=14)),
                ('numero_Documento', models.CharField(max_length=20)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresas')),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Fornecedores')),
            ],
            options={
                'verbose_name_plural': 'Lancamentos a Pagar',
            },
        ),
        migrations.CreateModel(
            name='LancamentosReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Vencimento', models.DateField()),
                ('data_Emissao', models.DateField()),
                ('valor_Titulo', models.CharField(max_length=14)),
                ('numero_Documento', models.CharField(max_length=20)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Clientes')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresas')),
            ],
            options={
                'verbose_name_plural': 'Lancamentos a Receber',
            },
        ),
        migrations.CreateModel(
            name='PlanosDeContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=18)),
                ('tipo_Conta', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
                ('caixa', models.BooleanField(default=False)),
                ('banco', models.BooleanField(default=False)),
                ('cliente', models.BooleanField(default=False)),
                ('fornecedor', models.BooleanField(default=False)),
                ('entrada_Recurso', models.BooleanField(default=False)),
                ('saida_Recurso', models.BooleanField(default=False)),
                ('Conta_Bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ContasBancarias')),
            ],
            options={
                'verbose_name_plural': 'Planos de Contas',
            },
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=14)),
                ('numero', models.CharField(max_length=15)),
                ('data_Vencimento', models.DateField()),
                ('data_Emissao', models.DateField()),
                ('data_Disponibilidade', models.DateField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Clientes')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresas')),
                ('Forma_Pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.FormasPagamento')),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Fornecedores')),
                ('Plano_De_Contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PlanosDeContas')),
            ],
            options={
                'verbose_name_plural': 'Tesourarias',
            },
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='Forma_Pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.FormasPagamento'),
        ),
        migrations.AddField(
            model_name='baixasreceber',
            name='Lancamento_Receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.LancamentosReceber'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='Forma_Pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.FormasPagamento'),
        ),
        migrations.AddField(
            model_name='baixaspagar',
            name='Lancamento_Receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.LancamentosReceber'),
        ),
    ]
